// export { TALI } from '../../../../GitHub/js-max-pub/'tali.js/mod.js'
// export { parseDate, isoDate, isoDateTime, format as dateFormat, humanDuration, date } from '../../../../GitHub/js-max-pub/'std/date.js'
// export { intersection, difference, sortBy, cluster, unique } from '../../../../GitHub/js-max-pub/'std/array.js'
// let base = '../../../../GitHub/js-max-pub/'
export { sum, arithmeticMean, median, pretty, prettyNumber, standardDeviation, medianAbsoluteDeviation } from '../../../../GitHub/js-max-pub/std/number.js'
// export { keep, mapValues, filter as dictFilter, sortByKey } from '../../../../GitHub/js-max-pub/std/object.js'
export { $, $$, download } from '../../../../GitHub/js-max-pub/std/dom.js'
export { keep } from '../../../../GitHub/js-max-pub/std/object.js'
export { unique } from '../../../../GitHub/js-max-pub/std/array.js'
// export { template, importable } from '../../../../GitHub/js-max-pub/'template/mod.js'
// export * from '../../../../GitHub/js-max-pub/pager/mod.js'
// export { pseudonymize, MAP as pseudoMAP } from '../../../../GitHub/js-max-pub/random/mod.js'
export { Thread } from '../../../../GitHub/js-max-pub/thread.js/mod.js'
export { default as KV } from '../../../../GitHub/js-max-pub/idbkv/mod.js'
export { pseudonymize, MAP as pseudoMAP } from '../../../../GitHub/js-max-pub/random/mod.js'
// export * as pseudo from '../../../../GitHub/js-max-pub/random/mod.js'


